### ISSUE TITLE
CODE RUB: Cleanup Logging Broker

### ISSUE THREAD

**Issue by ShriHumrudha** [hassanhabib/Taarafo.Core#15]
We should always keep our code neat & tidy.

Targeting file: https://github.com/hassanhabib/Taarafo.Core/blob/master/Taarafo.Core/Brokers/Loggings/LoggingBroker.cs
1. Remove one extra line between line number 4 & 7
2. Order the implementation method to match the order in the interface

**Comment by wbalbo** [comment]
Hi, please assign this to me!

I didn't saw a CONTRIBUTING.md file but I can use the "normal way" by forking this project, creating a branch based on main, doing my changes, and making a PR, right?

Thanks.
