### ISSUE TITLE
CODE RUB: Parameter Alias

### ISSUE THREAD

**Issue by ShriHumrudha** [hassanhabib/Taarafo.Core#16]
Read the standard for parameter aliasing here - https://github.com/hassanhabib/CSharpCodingStandard/blob/master/Methods.md#104-passing-parameters

Target file: https://github.com/hassanhabib/Taarafo.Core/blob/master/Taarafo.Core/Models/Posts/Exceptions/PostDependencyException.cs

The base method takes a parameter name 'message' which is not being aliased here.

**Comment by wbalbo** [comment]
Hi, please assign this to me!

Thanks.
