### ISSUE TITLE
FOUNDATIONS: Retrieve All Groups

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Taarafo.Core#184]
This task is assigned to @evangelinedrink

**Comment by absundr** [comment]
is this done? I'd like to help if it isn't.

**Comment by evangelinedrink** [comment]
Hello,
No, this is not done. I'll try to finish it within a couple of days. If I
need help, I'll let you know.

Thank you,
Evangeline Drink

Le dim. 3 juil. 2022 à 09:53, Abhijith Sunder ***@***.***> a
écrit :

**Comment by evangelinedrink** [comment]
@absundr Sorry, I believe this Pull Request has been completed.  I think the Group Post Model hasn't been started yet, so you could work on it.

**Comment by absundr** [comment]
@evangelinedrink Alright, if you could create an issue for it. I'd be happy to take a look.

**Comment by evangelinedrink** [comment]
@absundr I created the issue for Retrieve All Group Posts. It is issue #226

**Comment by absundr** [comment]
@evangelinedrink ill take a look once I get free

**Comment by evangelinedrink** [comment]
@absundr Okay, sounds good.

**Comment by cjdutoit** [comment]
Closing issue as this has been completed on [#190](https://github.com/hassanhabib/Taarafo.Core/pull/190)
