### ISSUE TITLE
FOUNDATIONS: Remove Group

### ISSUE THREAD

**Issue by eriadhami** [hassanhabib/Taarafo.Core#203]
@hassanhabib since the Model and Broker is already in place can I continue with this bro?

**Comment by eriadhami** [comment]
@rcruzfreelance thanks bro. The PR you referenced is about removing Profile, meanwhile, I am talking about removing Group

**Comment by rcruzfreelance** [comment]
Oh wow im so sorry didnt read the full title

**Comment by rcruzfreelance** [comment]
I can still work on this task then

**Comment by cjdutoit** [comment]
Completed in #215
