### ISSUE TITLE
CODE RUB: Rename file GroupServiceTests.Logic.Create.cs to GroupServiceTests.Logic.Add.cs

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#237]

**Comment by codewithfan** [comment]
Hi @cjdutoit, I would love to fix this issue.

**Comment by cjdutoit** [comment]
Assigned to @codewithfan

**Comment by codewithfan** [comment]
Ready to be closed.

https://github.com/hassanhabib/Taarafo.Core/commit/068ed1ee83f7f5d5d07287d584ef5531c5ad7a41
