### ISSUE TITLE
FOUNDATIONS: Remove Group Post

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#241]
Dependant on #239

Implement the Remove Group Post on the GroupPostService foundation service.

**Comment by cjdutoit** [comment]
Assigned to @Rashidovicc

**Comment by cjdutoit** [comment]
@Rashidovicc, for this task you will need to follow TDD to implement it.  You will need to follow the commit steps of creating a failing test and then the passing test working your way up from the happy path to validations and then the exceptions.

If you are stuck,  go check out the [Taarafo videos on YouTube](https://www.youtube.com/watch?v=8JBJQqoJTe0&list=PLan3SCnsISTQNkgtVMqJu896TghXjGYzt)

Or have a look at the commit history for the items below to see the commit progression:
[FOUNDATIONS: Remove Post by Id #50](https://github.com/hassanhabib/Taarafo.Core/pull/50)

**Comment by jasurbekyusuf** [comment]
Can you please @cjdutoit  assign me this issue
