### ISSUE TITLE
FOUNDATIONS: Remove Post Impression

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#242]

**Comment by evangelinedrink** [comment]
@cjdutoit Hello! Is it possible to check the brokers that I did for the Post Impression model? The brokers are #232 , #235 and #236.

**Comment by Javlonbek-dev** [comment]
Can you please @cjdutoit assign me this issue

**Comment by cjdutoit** [comment]
Assigned to @Javlonbek-dev
