### ISSUE TITLE
FOUNDATIONS: Retrieve All Post Impressions

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#250]

**Comment by Dastanbayev** [comment]
I hope I did issue #250 correctly

**Comment by Javlonbek-dev** [comment]
Can you please @cjdutoit assign me this problem

**Comment by cjdutoit** [comment]
Assigned to @Javlonbek-dev

**Comment by Javlonbek-dev** [comment]
Hello Christo du Toit please check my PR for me
