### ISSUE TITLE
CODE RUB: Refactor Event.cs

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#253]
Fix the namespace [`Taarafo.Core.Models.NewFolder`](https://github.com/hassanhabib/Taarafo.Core/blob/master/Taarafo.Core/Models/Events/Event.cs#L9)

Change the property name [`MyProperty`](https://github.com/hassanhabib/Taarafo.Core/blob/master/Taarafo.Core/Models/Events/Event.cs#L22) to something more meaning full matching the data type

Change [`DateTime`](https://github.com/hassanhabib/Taarafo.Core/blob/master/Taarafo.Core/Models/Events/Event.cs#L16) to `DateTimeOffset` to be consistent with other code => `public DateTimeOffset CreatedDate { get; set; }`

Add `public DateTimeOffset UpdatedDate { get; set; }`

Update the migrations once the above changes has been made.

**Comment by cjdutoit** [comment]
@RajeswariGunturi would you like to give this a go?

**Comment by RajeswariGunturi** [comment]
Sure ! Glad to take a look in the next 1-2 days
