### ISSUE TITLE
FOUNDATIONS: Add Event

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#259]
Dependent on #254

**Comment by cjdutoit** [comment]
Assigned to @khusnii

**Comment by jasurbekyusuf** [comment]
Can you please @cjdutoit assign me this issue

**Comment by cjdutoit** [comment]
@jasurbekyusuf, this has been done by @khusnii.  Just waiting on some last changes on #343

**Comment by cjdutoit** [comment]
Assigned to @jasurbekyusuf.  Previous PR inactive.
