### ISSUE TITLE
FOUNDATIONS: Modify Event

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#262]
Dependent on #257

**Comment by cjdutoit** [comment]
Assigned to @khusnii

**Comment by jasurbekyusuf** [comment]
Can you please @cjdutoit assign me this issue

**Comment by iamDiyorjon** [comment]
Can I do this issue?

**Comment by rcruzfreelance** [comment]
@jasurbekyusuf are you still going to this one if not I can take this issue
