### ISSUE TITLE
CODE RUB: Update SameExceptionAs for GroupService Unit Tests

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/Taarafo.Core#267]
1. Update the SameExceptionAs in the tests for groups

2. On all the validation and exception tests the `await Assert.ThrowsAsync` has moved up from the `then` into the `when` and we assigned the outcome of the `await Assert.ThrowsAsync` to a variable i.e. 
```
            GroupValidationException actualGroupValidationException =
               await Assert.ThrowsAsync<GroupValidationException>(
                   addGroupTask.AsTask);
```
3. In the `then` block we added 
```
            actualGroupValidationException.Should().BeEquivalentTo(
                expectedGroupValidationException);
```
4. Convert all instances of `() => addGroupTask.AsTask()` to `addGroupTask.AsTask`

**Comment by cjdutoit** [comment]
Assigned to @Mehdi-Aghaei

**Comment by Javlonbek-dev** [comment]
@cjdutoit  Can you assign me to this issue as it is not active yet?
