### ISSUE TITLE
FOUNDATIONS: Remove Post by Id

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Taarafo.Core#28]

**Comment by cjdutoit** [comment]
@hassanhabib you can assign this to me

**Comment by hassanhabib** [comment]
@cjdutoit done.

**Comment by cjdutoit** [comment]
@hassanhabib this can be closed.  @cacti79 has already completed the work.   ID: 985fad95 - 02/11/2021

**Comment by hassanhabib** [comment]
Done
