### ISSUE TITLE
ACCEPTANCE: POST Post

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Taarafo.Core#39]
Learn more about acceptance tests here:
https://www.youtube.com/watch?v=WWN-9ahbdIU

**Comment by stasnowak** [comment]
@hassanhabib working on it

**Comment by stasnowak** [comment]
resolve #39

**Comment by hassanhabib** [comment]
@stasnowak  yeah ideally if you said Closed it should do that automatically. But then again github has been acting funny - so I am not surprised it didn't.
