### ISSUE TITLE
Comment Model Suggestion 

### ISSUE THREAD

**Issue by ahmednreldin** [hassanhabib/Taarafo.Core#8]
Hello Eng/ Hassan

Here's my suggestion for Comment model 

![image](https://user-images.githubusercontent.com/44178039/127709083-a48cdcc1-30e7-4b1f-93e4-ae2e365b0e9b.png)

RelationShip for the model I think about 
* Post will have one or many comments, 
* Author will have one or many comments, 
* Comment itself will have no comment or one , many comments ( i.e replies on a comment)

i'm not sure about comment state will be suitable or instead add comment rate
some kind of enum contains rates or status of comment

**Comment by hassanhabib** [comment]
Closing and deferring to @cjdutoit for this discussion.
